### ISSUE TITLE
Why to use PorkLib and not others?

### ISSUE THREAD

**Issue by NycuRO** [PorkStudios/PorkLib#25]
Why not use Hikari and use PorkLib-Database?

Why not use math and use PorkLib-math?

Why not use raknet by Mojang and use PorkLib-minecraft?

Why not?

Why Porklib?

**Comment by NycuRO** [comment]
Why not use java primitives or https://github.com/generateme/fastmath and use porklib-math & porklib-primitives?

Why not use https://github.com/Auburns/FastNoise and use Porklib-noise?

**Comment by DaMatrix** [comment]
well let's just go through these examples one by one:
- `db` is not really a database software, it's a wrapper around other stuff for simplicity
- `math` is a library of shared math functions used throughout PorkLib, and isn't particularly useful by itself
- `minecraft` has nothing to do with RakNet whatsoever...
- `primitive` is more of a port of the Java collections API to use primitives, totally different intent than something like fastutil or Trove4j
- `noise` is in Java :P
- that "fastmath" thing you linked isn't related to either PorkLib's `math` module or `primitive`

PorkLib is for the most part is just a bunch of wrappers around other things to make stuff simpler and faster to implement, as well as being pretty finely tuned to my coding style. I have yet to get around to documenting a lot of things, so it's also not really ready to be used by other people.

Gonna be closing this issue as it's not actually an issue, but that said, if you have any other questions, feel free to ask them.
